import os
os.system('cat log/sugih.log')
os.system('ls')
os.system('cat log/kumbah.log')
os.system('ls')
os.system('cat log/bersinar.log')
os.system('ls')
os.system('cat log/mongo.log')
os.system('ls')
os.system('cat log/sudarmono.log')
os.system('ls')
os.system('cat log/hujansore.log')
os.system('ls')
os.system('cat log/jugnah.log')
os.system('ls')
os.system('cat log/pemuda.log')
os.system('ls')
os.system('cat log/thatsok.log')
os.system('ls')
os.system('cat log/telupapat.log')
os.system('ls')
os.system('cat log/belajarmenulis.log')
os.system('ls')
os.system('cat log/ritamusik.log')
os.system('ls')
os.system('cat log/tempurung.log')
os.system('ls')
os.system('cat log/mediasatwa.log')
os.system('ls')
os.system('cat log/bekerjakeras.log')
os.system('ls')
os.system('cat log/kickandy.log')
os.system('ls')
os.system('cat log/pakkartun.log')
os.system('ls')
os.system('cat log/singaraja.log')
os.system('ls')
os.system('cat log/likuikang.log')
os.system('ls')
os.system('cat log/istanaraja.log')
os.system('ls')
os.system('cat log/idapangesti.log')
os.system('ls')
os.system('cat log/hana.log')
os.system('ls')
os.system('cat log/putricuan.log')
os.system('ls')
os.system('cat log/lawkana.log')
os.system('ls')
os.system('cat log/agustina.log')
os.system('ls')
os.system('cat log/unyuAman.log')
os.system('ls')
os.system('cat log/afitaAman.log')
os.system('ls')
os.system('cat log/banyuseger.log')
os.system('ls')
os.system('cat log/saungreja.log')
os.system('ls')
os.system('cat log/mandalikasport.log')
os.system('ls')
os.system('cat log/petan.log')
os.system('ls')
os.system('cat log/misteripurba.log')
os.system('ls')
os.system('cat log/mbatar.log')
os.system('ls')
os.system('cat log/zezo.log')
os.system('ls')
os.system('cat log/cuacaburuk.log')
os.system('ls')
os.system('cat log/isthere.log')
os.system('ls')
os.system('cat log/konter.log')
os.system('ls')
os.system('cat log/ratubening.log')
os.system('ls')
os.system('cat log/esbuahseger.log')
os.system('ls')
os.system('cat log/dologan.log')
os.system('ls')
os.system('cat log/baangwelu.log')
os.system('ls')
os.system('cat log/beritapilpres.log')
os.system('ls')
os.system('cat log/bajatempur.log')
os.system('ls')
