import os
os.system('hiveengine balance -a ritamusik') 
os.system('hiveengine balance -a sugihbondo')
os.system('hiveengine balance -a kumbah')
os.system('hiveengine balance -a bekerjakeras')
os.system('hiveengine balance -a bersinar')
os.system('hiveengine balance -a mongoland')
os.system('hiveengine balance -a hujansore')
os.system('hiveengine balance -a jugnah')
os.system('hiveengine balance -a pemudatimur')
os.system('hiveengine balance -a thatsok')
os.system('hiveengine balance -a telupapat')
os.system('hiveengine balance -a belajarmenulis')
