import os
os.system('hiveengine balance -a kalagondang')
os.system('hiveengine balance -a pendekarsembara')
os.system('hiveengine balance -a hanamufidah')
os.system('hiveengine balance -a alfinlestari')
os.system('hiveengine balance -a agustinalifia')
os.system('hiveengine balance -a lawkana')
os.system('hiveengine balance -a unyuafita')
os.system('hiveengine balance -a afita73')
os.system('hiveengine balance -a shahidamuni')
os.system('hiveengine balance -a isnabaeti')
os.system('hiveengine balance -a syintiadevina')
os.system('hiveengine balance -a tariraider')
os.system('hiveengine balance -a pakualam')
os.system('hiveengine balance -a viasefiana')
