import os
os.system('hiveengine balance -a sugih >> log/sugih.log')
os.system('echo sugih > log/sugih.log')
os.system('hiveengine balance -a kumbah >> log/kumbah.log')
os.system('echo kumbah > log/kumbah.log')
os.system('hiveengine balance -a bersinar >> log/bersinar.log')
os.system('echo bersinar > log/bersinar.log')
os.system('hiveengine balance -a mongo >> log/mongo.log')
os.system('echo mongo > log/mongo.log')
os.system('hiveengine balance -a sudarmono >> log/sudarmono.log')
os.system('echo sudarmono > log/sudarmono.log')
os.system('hiveengine balance -a hujansore >> log/hujansore.log')
os.system('echo hujansore > log/hujansore.log')
os.system('hiveengine balance -a jugnah >> log/jugnah.log')
os.system('echo jugnah > log/jugnah.log')
os.system('hiveengine balance -a pemuda >> log/pemuda.log')
os.system('echo pemuda > log/pemuda.log')
os.system('hiveengine balance -a thatsok >> log/thatsok.log')
os.system('echo thatsok > log/thatsok.log')
os.system('hiveengine balance -a telupapat >> log/telupapat.log')
os.system('echo telupapat > log/telupapat.log')
os.system('hiveengine balance -a belajarmenulis >> log/belajarmenulis.log')
os.system('echo belajarmenulis > log/belajarmenulis.log')
os.system('hiveengine balance -a ritamusik >> log/ritamusik.log')
os.system('echo ritamusik > log/ritamusik.log')
os.system('hiveengine balance -a tempurung >> log/tempurung.log')
os.system('echo tempurung > log/tempurung.log')
os.system('hiveengine balance -a mediasatwa >> log/mediasatwa.log')
os.system('echo mediasatwa > log/mediasatwa.log')
os.system('hiveengine balance -a bekerjakeras >> log/bekerjakeras.log')
os.system('echo bekerjakeras > log/bekerjakeras.log')
os.system('hiveengine balance -a kickandy >> log/kickandy.log')
os.system('echo kickandy > log/kickandy.log')
os.system('hiveengine balance -a pakkartun >> log/pakkartun.log')
os.system('echo pakkartun > log/pakkartun.log')
os.system('hiveengine balance -a singaraja >> log/singaraja.log')
os.system('echo singaraja > log/singaraja.log')
os.system('hiveengine balance -a likuikang >> log/likuikang.log')
os.system('echo likuikang > log/likuikang.log')
os.system('hiveengine balance -a istanaraja >> log/istanaraja.log')
os.system('echo istanaraja > log/istanaraja.log')
os.system('hiveengine balance -a idapangesti >> log/idapangesti.log')
os.system('echo idapangesti > log/idapangesti.log')
os.system('hiveengine balance -a hana >> log/hana.log')
os.system('echo hana > log/hana.log')
os.system('hiveengine balance -a putricuan >> log/putricuan.log')
os.system('echo putricuan > log/putricuan.log')
os.system('hiveengine balance -a lawkana >> log/lawkana.log')
os.system('echo lawkana > log/lawkana.log')
os.system('hiveengine balance -a agustina >> log/agustina.log')
os.system('echo agustina > log/agustina.log')
os.system('hiveengine balance -a unyuAman >> log/unyuAman.log')
os.system('echo unyuAman > log/unyuAman.log')
os.system('hiveengine balance -a afitaAman >> log/afitaAman.log')
os.system('echo afitaAman > log/afitaAman.log')
os.system('hiveengine balance -a banyuseger >> log/banyuseger.log')
os.system('echo banyuseger > log/banyuseger.log')
os.system('hiveengine balance -a saungreja >> log/saungreja.log')
os.system('echo saungreja > log/saungreja.log')
os.system('hiveengine balance -a mandalikasport >> log/mandalikasport.log')
os.system('echo mandalikasport > log/mandalikasport.log')
os.system('hiveengine balance -a petan >> log/petan.log')
os.system('echo petan > log/petan.log')
os.system('hiveengine balance -a misteripurba >> log/misteripurba.log')
os.system('echo misteripurba > log/misteripurba.log')
os.system('hiveengine balance -a mbatar >> log/mbatar.log')
os.system('echo mbatar > log/mbatar.log')
os.system('hiveengine balance -a zezo >> log/zezo.log')
os.system('echo zezo > log/zezo.log')
os.system('hiveengine balance -a cuacaburuk >> log/cuacaburuk.log')
os.system('echo cuacaburuk > log/cuacaburuk.log')
os.system('hiveengine balance -a isthere >> log/isthere.log')
os.system('echo isthere > log/isthere.log')
os.system('hiveengine balance -a konter >> log/konter.log')
os.system('echo konter > log/konter.log')
os.system('hiveengine balance -a ratubening >> log/ratubening.log')
os.system('echo ratubening > log/ratubening.log')
os.system('hiveengine balance -a esbuahseger >> log/esbuahseger.log')
os.system('echo esbuahseger > log/esbuahseger.log')
os.system('hiveengine balance -a dologan >> log/dologan.log')
os.system('echo dologan > log/dologan.log')
os.system('hiveengine balance -a baangwelu >> log/baangwelu.log')
os.system('echo baangwelu > log/baangwelu.log')
os.system('hiveengine balance -a beritapilpres >> log/beritapilpres.log')
os.system('echo beritapilpres > log/beritapilpres.log')
os.system('hiveengine balance -a bajatempur >> log/bajatempur.log')
os.system('echo bajatempur > log/bajatempur.log')
